name: Sync Templates to All Private Repos

on:
    workflow_dispatch:

jobs:
    sync-templates:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
            GH_USER: embedglobal

        steps:
            - name: Checkout org-templates
              uses: actions/checkout@v3

            - name: Install jq
              run: sudo apt-get install -y jq

            - name: Fetch all private repos and sync
              run: |
                  echo "Fetching private repos for $GH_USER..."

                  # Fetch all private repos (owned by user/org)
                  curl -s -H "Authorization: Bearer $GH_TOKEN" \
                       -H "Accept: application/vnd.github+json" \
                       "https://api.github.com/orgs/$GH_USER/repos?per_page=100&type=private" \
                  | jq -r '.[].full_name' > repos.txt

                  echo "Found repos:"
                  cat repos.txt

                  # Loop through repos and sync templates
                  while IFS= read -r REPO; do
                    REPO_NAME=$(basename "$REPO")

                    # Skip excluded repos
                    if [[ "$REPO_NAME" == ".github-private" ]]; then
                    echo "Skipping $REPO_NAME..."
                    continue
                    fi  
                    
                    echo "Syncing to $REPO..."

                    git clone https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git repo-dir
                    cd repo-dir
                    
                    for BRANCH in main staging; do
                        if git ls-remote --heads origin $BRANCH | grep -q $BRANCH; then
                            echo "Branch '$BRANCH' exists. Syncing templates..."

                            git checkout $BRANCH

                            mkdir -p .github/ISSUE_TEMPLATE
                            rm -rf .github/ISSUE_TEMPLATE/*
                            cp -r ../ISSUE_TEMPLATE/* .github/ISSUE_TEMPLATE/

                            mkdir -p .github
                            cp ../PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md

                            git config user.name "GitHub Actions"
                            git config user.email "actions@github.com"

                            git add .github
                            git commit -m "chore: sync issue and PR templates" || echo "No changes to commit"
                            git push origin $BRANCH
                        else
                            echo "Branch '$BRANCH' does not exist in $REPO. Skipping..."
                        fi
                        done

                    cd ..
                    rm -rf repo-dir
                  done < repos.txt
